### ISSUE TITLE
cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by OoAnikioO** [QodiCat/IC-Light-sd-webui#10]
i have this error

卸载模型！
Loading weights from local directory
加载模型！
Traceback (most recent call last):
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\extensions\IC-Light-SD-WebUI\process_fc.py", line 387, in process_relight
    results = process(input_fg, prompt, image_width, image_height, num_samples, seed, steps, a_prompt, n_prompt, cfg, highres_scale, highres_denoise, lowres_denoise, bg_source)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\extensions\IC-Light-SD-WebUI\process_fc.py", line 302, in process
    concat_conds = vae.encode(concat_conds).latent_dist.mode() * vae.config.scaling_factor
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\models\autoencoders\vae.py", line 175, in forward
    sample = self.mid_block(sample)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 738, in forward
    hidden_states = attn(hidden_states, temb=temb)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\models\attention_processor.py", line 522, in forward
    return self.processor(
  File "E:\StableDiffusion\Packages\Stable Diffusion WebUI\venv\lib\site-packages\diffusers\models\attention_processor.py", line 1279, in __call__
    hidden_states = F.scaled_dot_product_attention(
RuntimeError: cutlassF: no kernel found to launch!

all models are present and detected

**Comment by zebra3141592** [comment]
same problem,did you solve it?
