### ISSUE TITLE
Error executing callback ui_tabs_callback for D:\picture\sd-webui-aki-v4.7\extensions\IC-Light-SD-WebUI\scripts\ic_light_extension.py

### ISSUE THREAD

**Issue by toouki** [QodiCat/IC-Light-sd-webui#3]
*** Error executing callback ui_tabs_callback for D:\picture\sd-webui-aki-v4.7\extensions\IC-Light-SD-WebUI\scripts\ic_light_extension.py
    Traceback (most recent call last):
      File "D:\picture\sd-webui-aki-v4.7\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\picture\sd-webui-aki-v4.7\extensions\IC-Light-SD-WebUI\scripts\ic_light_extension.py", line 45, in on_ui_tab
        install()
      File "D:\picture\sd-webui-aki-v4.7\extensions\IC-Light-SD-WebUI\scripts\ic_light_extension.py", line 39, in install
        launch.run_pip("uninstall -y diffusers", "uninstalling diffusers due to version mismatch", live=False)
      File "<enhanced_experience patches.progress.launch>", line 49, in wrapped_run_pip
      File "D:\picture\sd-webui-aki-v4.7\modules\launch_utils.py", line 143, in run_pip
        return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
      File "D:\picture\sd-webui-aki-v4.7\modules\launch_utils.py", line 115, in run
        raise RuntimeError("\n".join(error_bits))
    RuntimeError: Couldn't install uninstalling diffusers due to version mismatch.
    Command: "D:\picture\sd-webui-aki-v4.7\python\python.exe" -m pip uninstall -y diffusers --prefer-binary
    Error code: 2
    stderr:
    Usage:
      D:\picture\sd-webui-aki-v4.7\python\python.exe -m pip uninstall [options] <package> ...
      D:\picture\sd-webui-aki-v4.7\python\python.exe -m pip uninstall [options] -r <requirements file> ...

    no such option: --prefer-binary

**Comment by toouki** [comment]
Comment the following line and the environment will download normally:
        # if k == 'diffusers':
        #     import pkg_resources
        #     version = pkg_resources.get_distribution('diffusers').version
        #     if version != '0.27.2':
        #         launch.run_pip("uninstall -y diffusers", "uninstalling diffusers due to version mismatch", live=False)
        #         launch.run_pip("install "+"diffusers==0.27.2")

**Comment by toouki** [comment]
一坨大便，全是问题

**Comment by vasiluz** [comment]
The alternative is to install diffusers==0.27.2 manually in venv. I will reference my solution in other issue one more time https://github.com/QodiCat/IC-Light-SD-WebUI/issues/9#issuecomment-2227280045. Looks like it is quiet common problem.
