### ISSUE TITLE
TypeError: 'NoneType' object is not callable Error

### ISSUE THREAD

**Issue by DavideAlidosi** [QodiCat/IC-Light-sd-webui#4]
After install the extension and setup models directories, I have this error:
```
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "L:\indrema\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\indrema\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\indrema\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\indrema\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 386, in process_relight
    input_fg, matting = run_rmbg(input_fg)
  File "L:\indrema\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 262, in run_rmbg
    alpha = rmbg(feed)[0][0]
TypeError: 'NoneType' object is not callable
```
Any advice, please?

**Comment by DavideAlidosi** [comment]
Some other errors:
```
To create a public link, set `share=True` in `launch()`.
Startup time: 19.5s (prepare environment: 3.4s, import torch: 5.1s, import gradio: 1.1s, setup paths: 1.3s, initialize shared: 0.3s, other imports: 0.8s, load scripts: 2.9s, create ui: 3.8s, gradio launch: 0.4s, app_started_callback: 0.3s).Traceback (most recent call last):
  File "L:\indrema\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\indrema\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\indrema\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 43, in change_state1
    tokenizer = CLIPTokenizer.from_pretrained(sd_tokenizer_path)
  File "L:\indrema\system\python\lib\site-packages\transformers\tokenization_utils_base.py", line 1809, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'L:\indrema\webui\extensions/IC-Light-SD-WebUI/models/tokenizer/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'L:\indrema\webui\extensions/IC-Light-SD-WebUI/models/tokenizer/' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "L:\indrema\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\indrema\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\indrema\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\indrema\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 386, in process_relight
    input_fg, matting = run_rmbg(input_fg)
  File "L:\indrema\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 262, in run_rmbg
    alpha = rmbg(feed)[0][0]
TypeError: 'NoneType' object is not callable
```
This is my folder structure:
```
IC-Light-SD-WebUI
|_models
   |_iclight_sd15_fbc.safetensors
   |_iclight_sd15_fc.safetensors
   |_vae
   |_unet
   |_tokenizer
   |_text_encoder 
   |_rmbg
```

**Comment by DavideAlidosi** [comment]
Also I cannot load image from txt2img:
```
Traceback (most recent call last):
  File "L:\indrema\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\indrema\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\indrema\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\get_image.py", line 16, in get_img_from_txt2img
    latest_file = max(files, key=os.path.getmtime)
ValueError: max() arg is an empty sequence
```

**Comment by Fridemn** [comment]
models
   │  iclight_sd15_fbc.safetensors
   │  iclight_sd15_fc.safetensors
   │  model_download_here
   │
   ├─rmbg
   │      config.json
   │      model.pth
   │      model.safetensors
   │      pytorch_model.bin
   │
   ├─text_encoder
   │      config.json
   │      model.safetensors
   │      pytorch_model.bin
   │
   ├─tokenizer
   │      merges.txt
   │      special_tokens_map.json
   │      tokenizer_config.json
   │      vocab.json
   │
  ├─unet
   │      config.json
   │      diffusion_pytorch_model.bin
   │      diffusion_pytorch_model.safetensors
   │
   └─vae
           config.json
           diffusion_pytorch_model.bin
           diffusion_pytorch_model.safetensors
           
This is my folder structure，you need download all these contents,and make sure their names right.(because huggingface may change name).Now this installation method is quite troublesome.I will optimize right now.

**Comment by DavideAlidosi** [comment]
Thank you very much for the support! I was able to use the extension correctly after checking the structure and name of the files!
There remains the problem of directly loading images from txt2img but I will create an issue on purpose.

**Comment by DavideAlidosi** [comment]
I have done some testing and it seems that .safesensor files are sufficed to make the extension work. This saves some disk space.

**Comment by 3blackbar** [comment]
I have iclight safetensors inside extensions/iclight/models/  but your extension tells me i dont have them in folder.
I think you need more robust downloader - it does not work at all and does not even print error to commandline whats up when i click on it.
And model checker... it does not work as well cause the files are there, all 3 safetensors and names are matching.
    with open(path, 'wb') as out_file:
FileNotFoundError: [Errno 2] No such file or directory: './extensions/IC-Light-SD-WebUI/models/iclight_sd15_fc.safetensors'

**Comment by 3blackbar** [comment]
also i dont want to use realistic vision i wanna use my own safetensors , cant you just give an option for this
