### ISSUE TITLE
Currently it seems that loading from t2i and i2i does not work. (ValueError: max() arg is an empty sequence)

### ISSUE THREAD

**Issue by DavideAlidosi** [QodiCat/IC-Light-sd-webui#5]
Currently I can only use the extension by uploading images from the hard drive, if I try to upload images from t2i or i2i I get the following error:
```
Traceback (most recent call last):
  File "L:\indrema\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\indrema\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\indrema\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\indrema\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\indrema\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\indrema\webui\extensions\IC-Light-SD-WebUI\get_image.py", line 27, in get_img_from_img2img
    latest_file = max(files, key=os.path.getmtime)
ValueError: max() arg is an empty sequence
```

**Comment by QodiCat** [comment]
Are you sure that you have already generated some images?

**Comment by QodiCat** [comment]
It seems that your output dictionary is empyt

**Comment by DavideAlidosi** [comment]
Of course I have generate an image, to test t2i and also i2i import functions.

**Comment by Fridemn** [comment]
I have two guesses:
1 Are you using Linux? We didn't differentiate between '\' and '/' during development. I resolved this issue in yesterday's update.
2 The implementation of the reading function is achieved by fetching the latest image from the 'outputs/txt2img-images' directory. So if the save path is different, it could lead to this problem.
I hope this can help you.

**Comment by DavideAlidosi** [comment]
I'm on Windows 10 and WebUI 1.8.0, my actuals output folders are the defaults ones:
`output\txt2img-images\date`
`output\img2img-images\date`

**Comment by DavideAlidosi** [comment]
Probably I've found the issue, you are using `outputs` folder instead of `output`, as system do.

**Comment by DavideAlidosi** [comment]
I've fixed, into the file get_image.py:
`Line: 9, "/outputs" to "/output"`
`Line: 20, "/outputs" to "/output"`

**Comment by DavideAlidosi** [comment]
I've also improving and fixing the save function of the extension.
process_fbc.py, line 407 and 408:
```
dateNow = datetime.now().strftime('%Y-%m-%d')
output_dir = str(paths.script_path) + ("/output/IC-Light/txt2img-images/" +dateNow)
```
process_fc.py, line 375 and 376:
```
dateNow = datetime.now().strftime('%Y-%m-%d')
output_dir = str(paths.script_path) + ("/output/IC-Light/txt2img-images/" +dateNow)
```
