### ISSUE TITLE
i have all the models and files needed, no errors when checking , but it still fails and does not work 

### ISSUE THREAD

**Issue by 3blackbar** [QodiCat/IC-Light-SD-WebUI#6]
File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fbc.py", line 54, in process_relight2
    input_fg, matting = run_rmbg(input_fg)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fbc.py", line 308, in run_rmbg
    alpha = rmbg(feed)[0][0]
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 44, in change_state1
    text_encoder = CLIPTextModel.from_pretrained(text_encoder_path)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 386, in process_relight
    input_fg, matting = run_rmbg(input_fg)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 262, in run_rmbg
    alpha = rmbg(feed)[0][0]
TypeError: 'NoneType' object is not callable

**Comment by kurajber** [comment]
Me too, manualy redownloaded models, still getting the same error.

  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\a1111\stable-diffusion-webui\extensions\IC-Light-sd-webui\process_fbc.py", line 113, in change_state2
    text_encoder = CLIPTextModel.from_pretrained(text_encoder_path)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\a1111\stable-diffusion-webui\extensions\IC-Light-sd-webui\process_fbc.py", line 54, in process_relight2
    input_fg, matting = run_rmbg(input_fg)
  File "D:\a1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\a1111\stable-diffusion-webui\extensions\IC-Light-sd-webui\process_fbc.py", line 308, in run_rmbg
    alpha = rmbg(feed)[0][0]
TypeError: 'NoneType' object is not callable

**Comment by QodiCat** [comment]
You may need check the structure of folder and change some names of model files.

**Comment by QodiCat** [comment]
> You may need check the structure of folder and change some names of model files.


You may need check the structure of folder and change some names of model files.

**Comment by QodiCat** [comment]
> File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 807, in run result = context.run(func, *args) File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper response = f(*args, **kwargs) File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fbc.py", line 54, in process_relight2 input_fg, matting = run_rmbg(input_fg) File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fbc.py", line 308, in run_rmbg alpha = rmbg(feed)[0][0] TypeError: 'NoneType' object is not callable Traceback (most recent call last): File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api result = await self.call_function( File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function prediction = await anyio.to_thread.run_sync( File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 807, in run result = context.run(func, *args) File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper response = f(*args, **kwargs) File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 44, in change_state1 text_encoder = CLIPTextModel.from_pretrained(text_encoder_path) File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 2604, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "F:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 450, in load_state_dict with safe_open(checkpoint_file, framework="pt") as f: safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall Traceback (most recent call last): File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api result = await self.call_function( File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function prediction = await anyio.to_thread.run_sync( File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 807, in run result = context.run(func, *args) File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper response = f(*args, **kwargs) File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 386, in process_relight input_fg, matting = run_rmbg(input_fg) File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "F:\stable-diffusion-webui\extensions\IC-Light-SD-WebUI\process_fc.py", line 262, in run_rmbg alpha = rmbg(feed)[0][0] TypeError: 'NoneType' object is not callable


You may need check the structure of folder and change some names of model files.

**Comment by kurajber** [comment]
Checked the file structure

> > You may need check the structure of folder and change some names of model files.
> 
> You may need check the structure of folder and change some names of model files.

Checked file structure, everything ok.
The filenames for models are ok too:
```
iclight_sd15_fbc.safetensors
iclight_sd15_fc.safetensors
```
The only discrepancy I noticed is that the fc model downloaded via extension is 3GB, and the one I got from Huggingface is 1.7GB. Tried both of them, same error.

**Comment by AlUlkesh** [comment]
When I just downloaded from huggingface some filenames were changed. For example
`vae/config.json` becomes `vae/vae_config.json`
You can check this, and if it is true for you, rename them to their original name.

**Comment by vasiluz** [comment]
I had the same issue with 'NoneType' object message. If all filenames are correct try to check and uncheck "Use FC" checkbox and re-run generation after each check-uncheck. This solved the issue for me. Looks like something with initialization in the code.
