### ISSUE TITLE
同下面的报错

### ISSUE THREAD

**Issue by tsjslgy** [QodiCat/IC-Light-sd-webui#7]
国内用户，直接度盘下载的，保证完整性一致，开始打开没有选项卡，来找原因结果已经有人提了，注释了问题的几行后选卡出现。正要高兴的时候，第二个错来了，同楼下的几位。于是乎仔细核对了文件名，又跑到hg 上核对了一次，开了魔法和不开魔法都尝试过，结果还是一样。
SD-WebUI Launcher Diagnostic File

Date: 2024-06-10 03:05:31
Launcher Version: 2.8.4.338
Data File Version: 2024-05-21 11:30
SD-WebUI Version: 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0 (2024-04-22 23:00:36)
Working Directory: I:\AI\webui\sd-webui-aki-v4.1
------------------------
System Information: 
OS: Microsoft Windows NT 10.0.19045.0
CPU: 12 cores
Memory Size: 65536 MB
Page File Size: 0 MB

NVIDIA Management Library:
  NVIDIA Driver Version: 555.99
  NVIDIA Management Library Version: 12.555.99

CUDA Driver:
  Version: 12050
  Devices: 
    00000000:01:00.0 0: NVIDIA GeForce RTX 3060 [86] 12 GB

NvApi:
  Version: 55599 r555_97

HIP Driver:
  Not Available

DirectML Driver: 
  Devices: 
    9351 0: NVIDIA GeForce RTX 3060 11 GB
    9351 1: NVIDIA GeForce RTX 3060 11 GB

Intel Level Zero Driver:
  Not Available

------------------------
Traceback (most recent call last):
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "I:\AI\webui\sd-webui-aki-v4.1\extensions\IC-Light-SD-WebUI\process_fc.py", line 387, in process_relight
    results = process(input_fg, prompt, image_width, image_height, num_samples, seed, steps, a_prompt, n_prompt, cfg, highres_scale, highres_denoise, lowres_denoise, bg_source)
  File "I:\AI\webui\sd-webui-aki-v4.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "I:\AI\webui\sd-webui-aki-v4.1\extensions\IC-Light-SD-WebUI\process_fc.py", line 307, in process
    latents = t2i_pipe(
TypeError: 'NoneType' object is not callable
------------------------
Fault Traceback: 
Not Available
![01](https://github.com/QodiCat/IC-Light-SD-WebUI/assets/56958241/e6887979-35f7-41ea-a7dc-8d328f80a652)
![20](https://github.com/QodiCat/IC-Light-SD-WebUI/assets/56958241/695254d3-a4de-49a1-afb0-97409203c8f7)

**Comment by vasiluz** [comment]
I had the same "NoneType" error message few times. I did not analyzed the code, but looks like checking and unchecking "Use FC" checkbox few times and re-running generation solved it for me. Try uncheck "Use FC" and run generation, then check "Use FC" again and run generation.
I can assume that there is no default value assigned to some object somewhere in the code.
