### ISSUE TITLE
Install all model and check name, but get this error.

### ISSUE THREAD

**Issue by offerz-off** [QodiCat/IC-Light-sd-webui#8]
*** Error loading script: ic_light_extension.py
    Traceback (most recent call last):
      File "G:\Data\Packages\Stable Diffusion WebUI\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\Data\Packages\Stable Diffusion WebUI\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\Data\Packages\Stable Diffusion WebUI\extensions\IC-Light-SD-WebUI\scripts\ic_light_extension.py", line 10, in <module>
        from gradio_demo import iclight_demo
      File "G:\Data\Packages\Stable Diffusion WebUI\extensions\IC-Light-SD-WebUI\gradio_demo.py", line 3, in <module>
        from process_fc import process_relight,change_state1
      File "G:\Data\Packages\Stable Diffusion WebUI\extensions\IC-Light-SD-WebUI\process_fc.py", line 4, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline
    ModuleNotFoundError: No module named 'diffusers'

**Comment by offerz-off** [comment]
![Screenshot 2024-06-16 152815](https://github.com/QodiCat/IC-Light-SD-WebUI/assets/172960781/b0e5afd9-c48d-4e9c-b525-3b492367fb54)

**Comment by pttrwt** [comment]
![ภาพ](https://github.com/QodiCat/IC-Light-SD-WebUI/assets/40859919/6cd8208c-9ae7-4da3-86e0-50a01779f96f)

I try 'pip install diffusers' but problem still not resolve.

![ภาพ](https://github.com/QodiCat/IC-Light-SD-WebUI/assets/40859919/f5621c82-c406-4c71-9742-4dccd1ef11ab)

**Comment by vasiluz** [comment]
Looks like you need to install correct version of diffusers in venv for a1111. Try solution from my comment here https://github.com/QodiCat/IC-Light-SD-WebUI/issues/9#issuecomment-2227280045
